In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("adult.csv")
df.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [10]:
df.isnull().sum()

39                0
 State-gov        0
 77516            0
 Bachelors        0
 13               0
 Never-married    0
 Adm-clerical     0
 Not-in-family    0
 White            0
 Male             0
 2174             0
 0                0
 40               0
 United-States    0
 <=50K            0
dtype: int64

In [11]:
df.columns=['Age','Workclass','Fnlwgt','Education','education_num','marital_status','occupation','relationship','race','sex',
            'capital_gain','capital_loss','hours_per_week','native_country','income']

In [12]:
df.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        marital_status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

In [13]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
32555    False
32556    False
32557    False
32558    False
32559    False
Length: 32560, dtype: bool

In [14]:
df.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [15]:
print(df['Workclass'].value_counts())
print(df['marital_status'].value_counts())

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: Workclass, dtype: int64
 Married-civ-spouse       14976
 Never-married            10682
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: marital_status, dtype: int64


In [16]:
print(df['occupation'].value_counts())
print(df['relationship'].value_counts())
print(df['race'].value_counts())

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3769
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 ?                    1843
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: occupation, dtype: int64
 Husband           13193
 Not-in-family      8304
 Own-child          5068
 Unmarried          3446
 Wife               1568
 Other-relative      981
Name: relationship, dtype: int64
 White                 27815
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name: race, dtype: int64


In [17]:
print(df['Education'].value_counts())
print(df['sex'].value_counts())

 HS-grad         10501
 Some-college     7291
 Bachelors        5354
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: Education, dtype: int64
 Male      21789
 Female    10771
Name: sex, dtype: int64


In [18]:
print(df['native_country'].value_counts())
print(df['income'].value_counts())

 United-States                 29169
 Mexico                          643
 ?                               583
 Philippines                     198
 Germany                         137
 Canada                          121
 Puerto-Rico                     114
 El-Salvador                     106
 India                           100
 Cuba                             95
 England                          90
 Jamaica                          81
 South                            80
 China                            75
 Italy                            73
 Dominican-Republic               70
 Vietnam                          67
 Guatemala                        64
 Japan                            62
 Poland                           60
 Columbia                         59
 Taiwan                           51
 Haiti                            44
 Iran                             43
 Portugal                         37
 Nicaragua                        34
 Peru                             31
 

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
lb = LabelEncoder()
df['Workclass'] = lb.fit_transform(df['Workclass'])
df['relationship'] = lb.fit_transform(df['relationship'])
df['occupation'] = lb.fit_transform(df['occupation'])
df['marital_status'] = lb.fit_transform(df['marital_status'])
df['race'] = lb.fit_transform(df['race'])
df['Education'] = lb.fit_transform(df['Education'])
df['sex'] = lb.fit_transform(df['sex'])
df['native_country'] = lb.fit_transform(df['native_country'])
df['income'] = lb.fit_transform(df['income'])

In [21]:
df.dtypes

Age               int64
Workclass         int32
Fnlwgt            int64
Education         int32
education_num     int64
marital_status    int32
occupation        int32
relationship      int32
race              int32
sex               int32
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int32
income            int32
dtype: object

In [22]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [23]:
print(x.shape)
print(y.shape)

(32560, 14)
(32560,)


In [24]:
x.head(32561)

Age  Workclass  Fnlwgt  Education  education_num  marital_status  \
0       50          6   83311          9             13               2   
1       38          4  215646         11              9               0   
2       53          4  234721          1              7               2   
3       28          4  338409          9             13               2   
4       37          4  284582         12             14               2   
...    ...        ...     ...        ...            ...             ...   
32555   27          4  257302          7             12               2   
32556   40          4  154374         11              9               2   
32557   58          4  151910         11              9               6   
32558   22          4  201490         11              9               4   
32559   52          5  287927         11              9               2   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
0               4             0     4    1             0             0   
1               6             1     4    1             0             0   
2               6             0     2    1             0             0   
3              10             5     2    0             0             0   
4               4             5     4    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32555          13             5     4    0             0             0   
32556           7             0     4    1             0             0   
32557           1             4     4    0             0             0   
32558           1             3     4    1             0             0   
32559           4             5     4    0         15024             0   

       hours_per_week  native_country  
0                  13              39  
1                  40              39  
2                  40              39  
3                  40               5  
4                  40              39  
...               ...             ...  
32555              38              39  
32556              40              39  
32557              40              39  
32558              20              39  
32559              40              39  

[32560 rows x 14 columns]

In [25]:
y.head(32561)

0        0
1        0
2        0
3        0
4        0
        ..
32555    0
32556    1
32557    0
32558    0
32559    1
Name: income, Length: 32560, dtype: int32

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(26048, 14)
(6512, 14)
(26048,)
(6512,)


In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [29]:
def apply_model(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    ypred = model.predict(x_test)
    print('Predictions\n',ypred)
    print('Training Score',model.score(x_train,y_train))
    print('Testing Score',model.score(x_test,y_test))
    cm = confusion_matrix(y_test,ypred)
    print('Confusion_matrix\n',cm)
    print('Classification_report\n',classification_report(y_test,ypred))

In [30]:
m1 = DecisionTreeClassifier(criterion='entropy',max_depth=14,min_samples_split=150)
apply_model(m1,x_train,x_test,y_train,y_test)

Predictions
 [0 0 0 ... 0 0 0]
Training Score 0.8683200245700246
Testing Score 0.8556511056511057
Confusion_matrix
 [[4680  230]
 [ 710  892]]
Classification_report
               precision    recall  f1-score   support

           0       0.87      0.95      0.91      4910
           1       0.80      0.56      0.65      1602

    accuracy                           0.86      6512
   macro avg       0.83      0.75      0.78      6512
weighted avg       0.85      0.86      0.85      6512



In [31]:
mrate1 = float((1 - accuracy_score(y_test,m1.predict(x_test))))
print('mislassification rate for decision tree classifier',mrate1)

mislassification rate for decision tree classifier 0.1443488943488943


In [32]:
m2 = RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=9,min_samples_split=12)
apply_model(m2,x_train,x_test,y_train,y_test)

Predictions
 [0 0 1 ... 0 0 0]
Training Score 0.8624846437346437
Testing Score 0.8536547911547911
Confusion_matrix
 [[4708  202]
 [ 751  851]]
Classification_report
               precision    recall  f1-score   support

           0       0.86      0.96      0.91      4910
           1       0.81      0.53      0.64      1602

    accuracy                           0.85      6512
   macro avg       0.84      0.75      0.77      6512
weighted avg       0.85      0.85      0.84      6512



In [33]:
mrate2 = float((1 - accuracy_score(y_test,m2.predict(x_test))))
print('mislassification rate for random forest classifier',mrate2)

mislassification rate for random forest classifier 0.14634520884520885


In [34]:
m3 = KNeighborsClassifier(n_neighbors=19)
apply_model(m3,x_train,x_test,y_train,y_test)

Predictions
 [0 0 0 ... 1 0 0]
Training Score 0.8039772727272727
Testing Score 0.7980651105651105
Confusion_matrix
 [[4845   65]
 [1250  352]]
Classification_report
               precision    recall  f1-score   support

           0       0.79      0.99      0.88      4910
           1       0.84      0.22      0.35      1602

    accuracy                           0.80      6512
   macro avg       0.82      0.60      0.61      6512
weighted avg       0.81      0.80      0.75      6512



In [35]:
mrate3 = float((1 - accuracy_score(y_test,m3.predict(x_test))))
print('mislassification rate for KNeighbours classifier',mrate3)

mislassification rate for KNeighbours classifier 0.20193488943488946


In [36]:
m4 = LogisticRegression(solver='liblinear')
apply_model(m4,x_train,x_test,y_train,y_test)

Predictions
 [1 0 0 ... 0 1 0]
Training Score 0.7894272113022113
Testing Score 0.7876228501228502
Confusion_matrix
 [[4664  246]
 [1137  465]]
Classification_report
               precision    recall  f1-score   support

           0       0.80      0.95      0.87      4910
           1       0.65      0.29      0.40      1602

    accuracy                           0.79      6512
   macro avg       0.73      0.62      0.64      6512
weighted avg       0.77      0.79      0.76      6512



In [37]:
mrate4 = float((1 - accuracy_score(y_test,m4.predict(x_test))))
print('mislassification rate for LogisticRegression classifier',mrate4)

mislassification rate for LogisticRegression classifier 0.21237714987714984


In [ ]:
m5 = SVC(kernel='linear',C=1)
apply_model(m5,x_train,x_test,y_train,y_test)

In [ ]:
mrate5 = float((1 - accuracy_score(y_test,m5.predict(x_test))))
print('mislassification rate for SVM classifier',mrate5)

#### the best model in this case is Random Forest Classifier with Training Score 0.862676597051597
#### Testing Score 0.8585687960687961 and misclassification rate of 0.1414312039312039